### ISSUE TITLE
Not show All SD Root folders when Bootprotect is enabled on Hekate

### ISSUE THREAD

**Issue by impeeza** [cathery/sys-ftpd#19]
I am using FW 13.0.0, Atmosphère 1.1.1 and Hekate 5.6.2.

If the key `bootprotect=1` is enabled on `hekate_ipl.ini` is supposed to hide the bootloader folder on the SD root.

But FTPD appears to stop listing folders when do not have access to that folder, so the SD root on a FTP client looks like

![image](https://user-images.githubusercontent.com/41979604/134793918-69798255-a249-4589-a39e-438784a8d655.png)

The strange is what others homebrew does show the complete folder structure on SD root, by example, NX-Shell shows all the folders:

![image](https://user-images.githubusercontent.com/41979604/135012849-30c4636a-4c0f-4af0-b11c-23dc11944ff0.png)

is like the code listing SD content do not catch exceptions so when error abort the listing processes.

**Comment by impeeza** [comment]
I have a addition to issue, this is triggered by enabling the key 
`bootprotect=1` on hekate_ipl.ini is supposed to hide the bootloader folder on the SD root, but hide a lot of folders,  the strange is others homebrew does see the complete folder structure on SD root, by example, NX-Shell shows all the folders:

![image](https://user-images.githubusercontent.com/41979604/135012849-30c4636a-4c0f-4af0-b11c-23dc11944ff0.png)

**Comment by ToxiClay** [comment]
OK, the fix for the bootprotect issue shouldn't be too intensive, as mtheall was able to produce a fixed version of FTPD in short order; hopefully, this means that it shouldn't be too hard to adapt sysmodule versions so that users can keep bootprotect enabled for safety.

**Comment by darkarrow** [comment]
Hello, just wanted to interject and say that I am having this issue as well.

Seems the ftp server doesn't know how to handle listing/not listing something that doesn't allow reading/writing and that's what the issue is.

I do get it to list shortly after setting bootprotect in hekate to on but then sometime latter it breaks and won't list the root of the sd card unless I disable bootprotect. Once I connect even though it won't let me list the root directory I can still go to different directories as long as I know the folder I want to switch to.

Now that I found an issue open for what I am having troubles with wanted to see if there is any time frame or intention to fixing this issue? Thanks.
